### ISSUE TITLE
can't run simple-browser-client

### ISSUE THREAD

**Issue by vrs1985** [Curb-v2/third-party-app-integration#2]
my environment 
windows 10 x64
node -v  8.10.0
npm -v 5.6.0

I clone repo than done npm install next I npm start but unfortunately I got error below

'http-server' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curb-simple-browser-client@1.0.0 start: `http-server -p 8000`
npm ERR! Exit status 1
npm ERR! Failed at the curb-simple-browser-client@1.0.0 start script.

**Comment by codyrushing** [comment]
@vrs1985 I have added the missing `http-server` dependency - it should work now.  Just run an `npm install` in the `simple-browser-client` directory and then `npm start`

**Comment by vrs1985** [comment]
yes, it works like a charm
