### ISSUE TITLE
"s" resolution returns 400

### ISSUE THREAD

**Issue by forresthopkinsa** [Curb-v2/third-party-app-integration#7]
docs/api.md says the following:

> `s`, `m`, `5m`, and `h` are the only allowed resolution values.

I tried this request:

`GET https://app.energycurb.com/api/v3/historical/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/5s/s`

And got the following response:

```
{
    "data": {
        "message": "\"resolution\" must be either \"m\" (for minutes), \"5m\" (for 5 minutes) \"h\" (for hours), or \"d\" (for days)"
    },
    "message": {
        "message": "\"resolution\" must be either \"m\" (for minutes), \"5m\" (for 5 minutes) \"h\" (for hours), or \"d\" (for days)"
    },
    "status": 400
}
```

**Comment by codyrushing** [comment]
Hi @forresthopkinsa , thanks for the issue.  We unfortunately no longer allowed seconds-level historical queries.  I have updated the API docs to reflect that.  We recommend using our websocket API if your application requires that level of granularity.

We also have a newer version of our API that will be out in the next couple of months.  Once it is available, this repo will be updated.  Please let us know if you have other questions
